replicaCount: 1

image:
  repository: mongo
  tag: 4.4.6
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 32000

persistence:
  enabled: true
  storageClass: microk8s-hostpath
  accessMode: ReadWriteOnce
  size: 8Gi

mongodb:
  username: myuser
  password: mypassword
  database: mydatabase
