image:
  repository: mongo
  tag: 4.4.6
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 36925

persistence:
  enabled: true
  storageClass: microk8s-hostpath
  accessMode: ReadWriteOnce
  size: 50Gi

mongodb:
  username: myuser
  password: mypassword
