apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
      targetPort: {{ .Values.service.nodePort}}
  selector:
    app: mongodb
